"""External compatibility facade for historical VoiceFlow imports.

Internal VoiceFlow modules must import focused owners directly. This module
contains no implementation and exists only to keep older external imports
working while the architecture evolves.
"""

from __future__ import annotations

from .config import (
    APP_DIR,
    APP_LOG_PATH,
    APP_NAME,
    CATEGORY_LOG_FILES,
    CATEGORY_LOG_PATHS,
    COMPUTE_TYPE_OPTIONS,
    CRASH_LOG_PATH,
    CUDA_REQUIRED_WINDOWS_DLLS,
    DEFAULT_CHANNELS,
    DEFAULT_HOTKEY,
    DEFAULT_SAMPLE_RATE,
    DIAGNOSTICS_LOG_PATH,
    DICTATION_TEXT_LOG_PATH,
    HOTKEY_CAPTURE_CLEAR_KEYS,
    HOTKEY_DEBOUNCE_SECONDS,
    HOTKEY_START_GUARD_SECONDS,
    HOTKEY_MODIFIER_ORDER,
    HOTKEY_MODIFIERS,
    HOTKEY_SPECIAL_KEYS,
    INFERENCE_DEVICE_OPTIONS,
    IS_WINDOWS,
    LAST_APP_LOG_PATH,
    LAST_CATEGORY_LOG_PATHS,
    LAST_CRASH_LOG_PATH,
    LAST_DIAGNOSTICS_LOG_PATH,
    LAST_DICTATION_TEXT_LOG_PATH,
    LAST_RUN_DIR,
    LAST_RUN_POINTER_PATH,
    LEGACY_SETTINGS_PATH,
    LOCAL_WHISPER_MODEL,
    LOG_DIR,
    MAX_RUN_LOG_DIRS,
    QUALITY_OPTIONS,
    RUN_LOG_DIR,
    RUN_LOG_STAMP,
    SETTINGS_DIR,
    SETTINGS_PATH,
    START_MINIMIZED,
    START_VISIBLE,
    STREAMING_INTERVAL_OPTIONS,
    STREAMING_MAX_SECONDS,
    STREAMING_MIN_SECONDS,
    STREAMING_MODE_OPTIONS,
    STREAMING_SPEED_OPTIONS,
    STREAMING_TRAILING_SILENCE_SECONDS,
    STREAM_FINAL_CHUNK_ON_STOP,
    STREAM_FINISH_TIMEOUT_SECONDS,
    STREAM_SENTENCE_PAUSE_SECONDS_BALANCE,
    STREAM_SENTENCE_PAUSE_SECONDS_FAST,
    STREAM_SENTENCE_PAUSE_SECONDS_QUALITY,
    WHISPER_MODEL_OPTIONS,
    WINDOWS_HOTKEY_HEARTBEAT_SECONDS,
    WINDOWS_HOTKEY_MIN_EDGE_GAP_SECONDS,
    WINDOWS_HOTKEY_POLL_INTERVAL_SECONDS,
    WINDOWS_HOTKEY_RELEASE_STABLE_SECONDS,
    WINDOWS_HOTKEY_STUCK_DOWN_LOG_SECONDS,
    WINDOWS_HOTKEY_VK,
    get_app_dir,
)
from .audio_devices import get_input_devices
from .dependencies import (
    Image,
    ImageDraw,
    WhisperModel,
    keyboard,
    np,
    pyautogui,
    pyperclip,
    pystray,
    sd,
)
from .diagnostics import (
    acquire_single_instance_lock,
    configure_logging,
    dependency_status,
    find_windows_dll,
    install_exception_logging,
    log_category,
    log_crash,
    log_dictation_text,
    log_event,
    log_exception,
    log_info,
    log_warning,
    windows_dll_search_dirs,
    write_diagnostics_snapshot,
)
from .hotkey_config import (
    canonical_hotkey,
    hotkey_to_windows_vk_options,
    hotkey_token_to_windows_vk_options,
    is_modifier_only_hotkey,
    is_valid_hotkey_non_modifier,
    normalize_hotkey,
    pretty_hotkey,
    repair_unreliable_modifier_only_hotkey,
    should_suppress_hotkey_keys,
    summarize_windows_hotkey_state,
    tk_event_to_hotkey_part,
)
from .settings import AppSettings, RuntimeSettings, SettingsStore
from .voice_commands import (
    VOICE_CONTROL_COMMANDS,
    normalize_voice_command_text,
    split_trailing_voice_control_command,
    split_unpunctuated_trailing_send_command,
    voice_control_command_from_text,
)
from .windows_insertion import (
    PasteTarget,
    get_paste_target,
    is_paste_target_active,
    restore_paste_target,
    send_ctrl_v_native,
)
from .windows_startup import (
    get_current_script_path,
    get_startup_command,
    is_windows_startup_enabled,
    set_windows_startup_enabled,
)
